//! Shared helpers for model validation tests.
//!
//! These tests compare Fracture inference engine output against PyTorch
//! reference tensors. They require:
//!
//! 1. Reference data generated by `scripts/dump_reference.py`
//! 2. A GGUF model file — set `FRACTURE_MODEL_PATH` env var
//!
//! Tests skip gracefully when either prerequisite is missing.

use std::path::PathBuf;

use fracture_core::ModelConfig;
use fracture_cuda::CudaBackend;
use fracture_engine::Engine;
use fracture_gguf::WeightStore;

/// Project root (two levels up from this crate's manifest dir).
pub fn project_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .to_path_buf()
}

/// Root of the reference tensor directory.
pub fn reference_dir() -> PathBuf {
    project_root().join("tests/reference")
}

/// Root of the golden output directory.
pub fn golden_dir() -> PathBuf {
    project_root().join("tests/golden")
}

/// Returns the GGUF model path from `FRACTURE_MODEL_PATH` env var.
pub fn model_path() -> Option<PathBuf> {
    let path = PathBuf::from(std::env::var("FRACTURE_MODEL_PATH").ok()?);
    if path.exists() {
        Some(path)
    } else {
        eprintln!(
            "FRACTURE_MODEL_PATH={} does not exist",
            path.display()
        );
        None
    }
}

/// Returns true if reference data has been generated.
pub fn has_reference_data() -> bool {
    reference_dir().join("prompt_0/logits.bin").exists()
}

/// Load the real Llama model from GGUF and create an inference engine.
///
/// Returns `None` if `FRACTURE_MODEL_PATH` is not set or the file doesn't exist.
pub fn setup_real_engine() -> Option<(Engine<CudaBackend>, ModelConfig)> {
    let path = model_path()?;
    let mut backend = CudaBackend::new(0).expect("CUDA backend creation failed");
    let weights =
        WeightStore::load(&path, &backend, None).expect("failed to load GGUF weights");
    let config = weights.config.clone();
    backend
        .precompute_rope_freqs(config.head_dim, config.rope_theta)
        .expect("RoPE precomputation failed");
    let engine = Engine::new(backend, weights, 0..config.num_layers);
    Some((engine, config))
}

/// Skip the calling test with a message. Returns from the caller.
#[macro_export]
macro_rules! skip {
    ($($arg:tt)*) => {{
        eprintln!("SKIPPED: {}", format!($($arg)*));
        return;
    }};
}
