//! Shared helpers for model validation tests.
//!
//! These tests compare Fracture inference engine output against PyTorch
//! reference tensors. They require:
//!
//! 1. Reference data generated by `scripts/dump_reference.py`
//! 2. A GGUF model file — set `FRACTURE_MODEL_PATH` env var
//!
//! Tests skip gracefully when either prerequisite is missing.

use std::path::PathBuf;

use fracture_core::ModelConfig;
use fracture_cuda::CudaBackend;
use fracture_engine::Engine;
use fracture_gguf::WeightStore;

/// Project root (two levels up from this crate's manifest dir).
pub fn project_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .to_path_buf()
}

/// Root of the reference tensor directory.
pub fn reference_dir() -> PathBuf {
    project_root().join("tests/reference")
}

/// Root of the golden output directory.
pub fn golden_dir() -> PathBuf {
    project_root().join("tests/golden")
}

/// Returns the GGUF model path from `FRACTURE_MODEL_PATH` env var.
pub fn model_path() -> Option<PathBuf> {
    let path = PathBuf::from(std::env::var("FRACTURE_MODEL_PATH").ok()?);
    if path.exists() {
        Some(path)
    } else {
        eprintln!(
            "FRACTURE_MODEL_PATH={} does not exist",
            path.display()
        );
        None
    }
}

/// Returns true if reference data has been generated.
pub fn has_reference_data() -> bool {
    reference_dir().join("prompt_0/logits.bin").exists()
}

/// Load the real Llama model from GGUF and create an inference engine.
///
/// Returns `None` if `FRACTURE_MODEL_PATH` is not set or the file doesn't exist.
pub fn setup_real_engine() -> Option<(Engine<CudaBackend>, ModelConfig)> {
    let path = model_path()?;
    let mut backend = CudaBackend::new(0).expect("CUDA backend creation failed");
    let weights =
        WeightStore::load(&path, &backend, None).expect("failed to load GGUF weights");
    let config = weights.config.clone();
    backend
        .precompute_rope_freqs(config.head_dim, config.rope_theta)
        .expect("RoPE precomputation failed");
    let engine = Engine::new(backend, weights, 0..config.num_layers);
    Some((engine, config))
}

/// Skip the calling test with a message. Returns from the caller.
#[macro_export]
macro_rules! skip {
    ($($arg:tt)*) => {{
        eprintln!("SKIPPED: {}", format!($($arg)*));
        return;
    }};
}

/// Path to the always-available fixture model.
pub fn fixture_model_path() -> PathBuf {
    project_root().join("tests/fixtures/tiny-llama.gguf")
}

/// Reference dump directory for the fixture model.
pub fn fixture_reference_dir() -> PathBuf {
    project_root().join("tests/reference-fixture")
}

/// Golden generation directory for the fixture model.
pub fn fixture_golden_dir() -> PathBuf {
    project_root().join("tests/golden-fixture")
}

/// Set up an engine using the committed fixture model. Always available
/// (no FRACTURE_MODEL_PATH required). Returns None only if CUDA is
/// unavailable on the host.
pub fn setup_fixture_engine() -> Option<(Engine<CudaBackend>, ModelConfig)> {
    let path = fixture_model_path();
    if !path.exists() {
        panic!(
            "fixture missing at {}; run scripts/build_fixture_model.py",
            path.display()
        );
    }
    let mut backend = CudaBackend::new(0).ok()?;
    let weights =
        WeightStore::load(&path, &backend, None).expect("fixture load failed");
    let config = weights.config.clone();
    backend
        .precompute_rope_freqs(config.head_dim, config.rope_theta)
        .ok()?;
    let engine = Engine::new(backend, weights, 0..config.num_layers);
    Some((engine, config))
}

#[derive(serde::Deserialize)]
pub struct Baselines {
    pub schema_version: u32,
    pub tolerance_factor: f32,
    pub baselines: std::collections::HashMap<String, BaselineEntry>,
}

#[derive(serde::Deserialize)]
pub struct BaselineEntry {
    pub max_abs_error: f32,
    #[serde(default)]
    pub notes: String,
}

pub fn load_baselines() -> Baselines {
    let path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent().unwrap().parent().unwrap()
        .join("tests/baselines/logit_baselines.json");
    let s = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("baselines file missing at {}: {e}", path.display()));
    serde_json::from_str(&s)
        .unwrap_or_else(|e| panic!("baselines parse failed: {e}"))
}

/// Assert that `observed` does not exceed the committed baseline by more than
/// the configured `tolerance_factor`. Panics if `key` is not present in the
/// JSON, or if the observed value is too large.
pub fn assert_within_baseline(key: &str, observed: f32, baselines: &Baselines) {
    let entry = baselines.baselines.get(key).unwrap_or_else(|| {
        panic!(
            "no baseline entry for key {key}; add it to tests/baselines/logit_baselines.json \
             or refresh via scripts/refresh_logit_baselines.py"
        )
    });
    let limit = entry.max_abs_error * baselines.tolerance_factor;
    assert!(
        observed <= limit,
        "{key}: max_abs_error={observed:.6} exceeds baseline {:.6} * {} = {limit:.6}\n\
         If this drift is expected, update tests/baselines/logit_baselines.json via \
         scripts/refresh_logit_baselines.py.",
        entry.max_abs_error,
        baselines.tolerance_factor
    );
}
